---
version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run deploy -- --token $FIREBASE_TOKEN
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
