name: Delivery
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
env:
  NODE_VERSION: '17'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: npm ci
        run: npm ci --production
      - name: npm run build
        run: npm run build
      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v2
        with:
          name: public_${{ github.sha }}
          path: public/*
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      # https://github.com/actions/download-artifact
      - uses: actions/download-artifact@v2
        with:
          name: public_${{ github.sha }}
          path: public
      - name: npm install
        run: npm install -g firebase-tools@$(node -p -e "require('./package.json').devDependencies['firebase-tools']")
      - name: firebase hosting:channel:create
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          channel=$(echo ${{ github.head_ref }} | tr _ -)
          firebase hosting:channel:create --token ${{ secrets.FIREBASE_TOKEN }} ${channel}
        continue-on-error: true
      - name: firebase hosting:channel:deploy
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          channel=$(echo ${{ github.head_ref }} | tr _ -)
          firebase hosting:channel:deploy --token ${{ secrets.FIREBASE_TOKEN }} ${channel}
      - name: firebase deploy
        if: ${{ github.event_name == 'push' }}
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
  notify:
    runs-on: ubuntu-latest
    needs:
      - deploy
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: npm install
        run: npm install -g firebase-tools@$(node -p -e "require('./package.json').devDependencies['firebase-tools']")
      - name: firebase hosting:channel:open
        id: firebase_hosting_channel_open
        run: |
          channel=$(echo ${{ github.head_ref }} | tr _ -)
          url=$(firebase hosting:channel:open --token ${{ secrets.FIREBASE_TOKEN }} ${channel} | awk '{ print $3 }')
          echo "::set-output name=url::${url}"
      # https://github.com/actions/github-script
      - uses: actions/github-script@v5
        env:
          URL: ${{ steps.firebase_hosting_channel_open.outputs.url }}
        with:
          script: |
            const body = `Preview: ${process.env.URL}`

            const options = github.rest.issues.listComments.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            })

            const comments = await github.paginate(options)
            const comment = comments.find(c => c.body == body)

            if (comment) {
              return
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            })
