name: Delivery
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # https://github.com/actions/setup-node/releases/tag/v4.3.0
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          cache: npm
          node-version-file: .node-version
      - name: install dependencies
        run: npm ci --production
      - name: build assets
        run: npm run build
      # https://github.com/actions/upload-artifact/releases/tag/v4.6.2
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: public_${{ github.sha }}
          path: public/*
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') == false }}
    needs:
      - build
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # https://github.com/actions/setup-node/releases/tag/v4.3.0
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          cache: npm
          node-version-file: .node-version
      # https://github.com/actions/download-artifact/releases/tag/v4.2.1
      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          name: public_${{ github.sha }}
          path: public
      # https://github.com/google-github-actions/auth/releases/tag/v2.1.8
      - uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935
        with:
          create_credentials_file: true
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: install firebase-tools
        run: npm install -g firebase-tools@$(node -p -e "require('./package.json').devDependencies['firebase-tools']")
      - name: create firebase hosting channel
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          channel=$(echo ${{ github.head_ref }} | tr _ -)
          firebase hosting:channel:create ${channel}
        continue-on-error: true
      - name: deploy to firebase hosting channel
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          channel=$(echo ${{ github.head_ref }} | tr _ -)
          firebase hosting:channel:deploy ${channel}
      - name: deploy to firebase
        if: ${{ github.event_name == 'push' }}
        run: firebase deploy
  notify:
    runs-on: ubuntu-latest
    needs:
      - deploy
    if: >-
      ${{
        contains(github.event.pull_request.labels.*.name, 'dependencies') == false &&
        github.event_name == 'pull_request'
      }}
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # https://github.com/actions/setup-node/releases/tag/v4.3.0
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          cache: npm
          node-version-file: .node-version
      # https://github.com/google-github-actions/auth/releases/tag/v2.1.8
      - uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935
        with:
          create_credentials_file: true
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: install firebase-tools
        run: npm install -g firebase-tools@$(node -p -e "require('./package.json').devDependencies['firebase-tools']")
      - name: set url for firebase hosting channel
        id: firebase_hosting_channel_open
        run: |
          channel=$(echo ${{ github.head_ref }} | tr _ -)
          url=$(firebase hosting:channel:open ${channel} | awk '{ print $3 }')
          echo "url=${url}" >> ${GITHUB_OUTPUT}
      # https://github.com/actions/github-script/releases/tag/v7.0.1
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        env:
          URL: ${{ steps.firebase_hosting_channel_open.outputs.url }}
        with:
          script: |
            const body = `Preview: ${process.env.URL}`

            const options = github.rest.issues.listComments.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            })

            const comments = await github.paginate(options)
            const comment = comments.find(c => c.body == body)

            if (comment) {
              return
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            })
  security_check:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # https://github.com/aquasecurity/trivy-action/releases/tag/0.28.0
      - uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2
        with:
          scan-ref: package-lock.json
          scan-type: fs
          trivy-config: .trivy.yaml
