name: Garbage Collect
on:
  pull_request:
    types:
      - closed
jobs:
  firebase_hosting:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout/releases/tag/v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # https://github.com/actions/setup-node/releases/tag/v4.3.0
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          cache: npm
          node-version-file: .node-version
      # https://github.com/google-github-actions/auth/releases/tag/v2.1.8
      - uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935
        with:
          create_credentials_file: true
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: install firebase-tools
        run: npm install -g firebase-tools@$(node -p -e "require('./package.json').devDependencies['firebase-tools']")
      - name: delete firebase hosting channel
        run: |
          channel=$(echo ${{ github.head_ref }} | tr _ -)
          firebase hosting:channel:delete -f ${channel}
        continue-on-error: true
