name: Garbage Collect
on:
  pull_request:
    branches:
      - master
    types:
      - closed
env:
  NODE_VERSION: '15'
jobs:
  firebase_hosting:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: npm install
        run: npm install -g firebase-tools@$(node -p -e "require('./package.json').devDependencies['firebase-tools']")
      - name: firebase hosting:channel:delete
        run: |
          channel=$(echo ${{ github.head_ref }} | tr _ -)
          firebase hosting:channel:delete -f --token ${{ secrets.FIREBASE_TOKEN }} ${channel}
        continue-on-error: true
