name: Garbage Collect
on:
  pull_request:
    types:
      - closed
jobs:
  firebase_hosting:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      # https://github.com/google-github-actions/auth
      - uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: install firebase-tools
        run: npm install -g firebase-tools@$(node -p -e "require('./package.json').devDependencies['firebase-tools']")
      - name: delete firebase hosting channel
        run: |
          channel=$(echo ${{ github.head_ref }} | tr _ -)
          firebase hosting:channel:delete -f ${channel}
        continue-on-error: true
